defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    date_fmt: "%F"

- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    categories: "news"
    date_fmt: "%F"

exclude:
- README.md
- Gemfile
- Gemfile.lock
- setup.sh
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- linuxaudio.code-workspace
- planet.db
- planet.ini
- planet.rb

name: planet.linuxaudio.org
markdown: Kramdown
highlighter: rouge

repository:
  branch: "master"
  url: "https://github.com/redtide/plutone"
